### ISSUE TITLE
annalyns-infiltration feedback

### ISSUE THREAD

**Issue by Kyle-ND** [exercism/java-analyzer#168]
it suggests that you should return the expression when check for fast attack but the logic is reversed e.g when the knight is awake you must return false and not true

**Comment by sanderploegsma** [comment]
Thanks for your feedback! I'm assuming you're talking about [this analyzer comment](https://github.com/exercism/website-copy/blob/57b0d2179161ee13a5793511d564bbd1129781be/analyzer-comments/java/annalyns-infiltration/avoid_boolean_literal_returns.md), correct?

The code in the comment is not supposed to give the solution for the exercise, only to serve as an example of how to directly return a boolean condition. If you have any suggestions on making that more clear in the comment, feel free to leave a comment here!
