### ISSUE TITLE
How can I contribute to this analyzer?

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java-analyzer#5]
Hey java-analyzer folks. I'd like to get involved in this project, but it looks like there is next to no tracking of anything. Can we use issues to track tasks and assign them to contributors? I don't know if the existing 3 contributors have any sort of process going at the present. Cheers!

PS: Perhaps we can also add some documentation on the README describing a project workflow of some kind and how to get involved...

**Comment by jmrunkle** [comment]
@Smarticles101 - any comments?

**Comment by Smarticles101** [comment]
Thanks for the ideas on documentation and tracking, you made good points.

I don’t have any issue tracking right now. I just opened #6 if you’d like to work on it. I’m a little busy right now but I should have a new computer coming in soon.
