### ISSUE TITLE
Solution directory structure

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java-analyzer#6]
Currently, the analyzer doesn’t expect any directory structure for a solution. It’s just looking for the solution files. While deployed, the analyzer is being passed the directory which contains `src/java/main/etc` and then the solution files. The analyzer should be patched to expect this directory structure.

[Background](https://exercism-team.slack.com/archives/CFMEG1H0C/p1559834002007400)

**Comment by jmrunkle** [comment]
I'll see if I understood this correctly. Let me know if I'm off-base.

**Comment by Smarticles101** [comment]
Closed by #7

**Comment by jmrunkle** [comment]
Although we have done exactly as it was described, it does not appear to have fixed the issue. I would like to know more about what is being passed to the analyzer. We may need to have a little side discussion to get a better idea of what exactly is going on here.
