### ISSUE TITLE
Remove comment to use `isEmpty()` from Hamming analyzer

### ISSUE THREAD

**Issue by manumafe98** [exercism/java-analyzer#94]
So I'm getting this recommendation on the hamming practice exercise.

![image](https://github.com/exercism/java-analyzer/assets/95315128/048410c7-92f4-4939-aa0d-f56c27bf6295)

And checking the solutions that are mostly like the one in as [reference](https://github.com/exercism/java/blob/main/exercises/practice/hamming/.meta/src/reference/java/Hamming.java) in the exercise definition, I'm not understanding how this helps improve the code.

Because if both strands are empty the code works properly and the count is 0, there is even a [test](https://github.com/exercism/java/blob/1a73c1e6c6de4b6224e25e996e653f7949e54bf3/exercises/practice/hamming/src/test/java/HammingTest.java#L10) that checks that

**Comment by sanderploegsma** [comment]
Thanks for the feedback! You make an excellent point, I think the logic in the analyzer was built before the exercise was updated here: https://github.com/exercism/java/commit/239ad3258c75262ff83e2fbe1606f07642d36bd8. Previously it expected students to explicitly not allow empty strands, but that was recently removed.

I think we should update the analyzer to reflect this. Would you be willing to open a PR to fix it?

**Comment by manumafe98** [comment]
> I think we should update the analyzer to reflect this. Would you be willing to open a PR to fix it?

Sure!
